### PR TITLE
[WIP] Visualizations

### PR DESCRIPTION
**Pull request by VineethKanaparthi**
* **Please check if the PR fulfills these requirements**
  - [x] The commit message follows our guidelines or the commits will be squashed into one.
  - [ ] Tests for the changes have been added.
  - [ ] Docs have been added / updated.

* **What kind of change does this PR introduce?** 
    ...

* **Does this PR introduce a breaking change?** 
No

* **This PR fixes/implements the following -**
  - [ ] Bokeh version of binary_visualize
  - [x] Made the bokeh plots interactive with hovering feature
  - [x] Added bokeh plots in notebooks

* **Closing issues**
    ...

### CODE REVIEW

**Comment by markroxor** [comment]
Fix the commit history by merging master.

**Comment by VineethKanaparthi** [comment]
Can you be more specific @markroxor ?

**Comment by markroxor** [comment]
check the 'files changed' section. It includes changes which are not induced by you.

**Comment by markroxor** [comment]
ping @VineethKanaparthi

**Pull request closed without merging**
